# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ab58cac6b6d3d38d015699de009895e5c4511a1f99995e895e89d07e4ba60e7d9698337012164a4e9c2fb6fa5c946449c1a708c4df5dbaeadae40fef75c2532e

test:
  secret_key_base: 29d80a6683b983efd505c421244284b1838453cb771605076aebab52a10fbfb1b8a2d554aefb4d256d49da7bfa24252f0eb6a7acc2d86b6bd081b9f0fdb9a728

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
