# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: af0689eedb18c1b09409d3e9c81d77c4f27a3bcf74d73a788bc21be978e19f609bb13382c53f8575fed105ccde5bcfb2e719e8afe9da755297aebb733ca707a0

test:
  secret_key_base: 52cd5ef02eee904255e835e4961b834a40c4c0103b80c5910bf8b0ad8dbff2e5a964408c0a046153b8ea2ed993f0b89ddb720d216f783c8b5786044d2929c1e5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
