# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4b9b1ec2d1932ddc6c45b67d4b4d8f46c026a14a029c44a7aca6ac07c10571fb2a61deb4d8f970d45801cbe7aa99f365370f9a6f876719b78cce0c5553bf3bed

test:
  secret_key_base: eb61d07214c072d30f9a28ea06afef1ed5ea126d1d21e5d9143e4b57ced4871c8c5cefc93c90934cd8b926f1950f068efdbe9b49560ac50c58e2575964d9e5dd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
